# This is a basic workflow to help you get started with Actions

name: Sync with Upstream

# Controls when the workflow will run
on:
  # schedule:
  #   - cron: '0/5 * * * *'
  #   - cron: "0 0 1 * *" # 1st day of every month

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup git
        run: |
          git config --global user.email "gh.leokim@gmail.com"
          git config --global user.name "Leo Kim"
          
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/PhonePe/pulse.git
          git fetch upstream

      # Runs a single command using the runners shell
      - name: Fetch upstream repository and merge
        run: |
          git checkout master
          git rebase upstream/master
          # git push origin master --force
